import type { AIApp, AppCategory } from "@/types";

export const apps: AIApp[] = [
  {
    id: "genesis-art",
    name: "Genesis Art",
    category: "Image",
    description: "Create stunning visuals from simple text prompts.",
    longDescription:
      "Genesis Art leverages state-of-the-art diffusion models to transform your textual ideas into breathtaking and unique images. Whether you're a digital artist, a designer, or just exploring creativity, Genesis Art provides the tools to bring your imagination to life.",
    features: ["Text-to-Image Generation", "Multiple Art Styles", "High-Resolution Output", "Custom Aspect Ratios"],
    rating: 4.8,
    url: "https://example.com/genesis-art",
    imageId: "img_gen_art",
  },
  {
    id: "scribe-ai",
    name: "ScribeAI",
    category: "Text",
    description: "Your AI-powered writing assistant for any content.",
    longDescription:
      "ScribeAI helps you overcome writer's block and craft compelling content effortlessly. From blog posts and marketing copy to emails and reports, ScribeAI provides suggestions, rephrasing, and tone adjustments to elevate your writing.",
    features: ["Content Generation", "Grammar & Style Checking", "Tone Analysis", "Plagiarism Detection"],
    rating: 4.6,
    url: "https://example.com/scribe-ai",
    imageId: "img_writer_assist",
  },
  {
    id: "codex-prime",
    name: "Codex Prime",
    category: "Code",
    description: "Generate, debug, and optimize code with AI.",
    longDescription:
      "Codex Prime is an essential tool for developers. It understands natural language prompts to generate boilerplate code, write complex functions, explain existing codebases, and help you debug faster. Supports over a dozen programming languages.",
    features: ["Code Generation", "Natural Language to Code", "Bug Detection", "Code Refactoring"],
    rating: 4.9,
    url: "https://example.com/codex-prime",
    imageId: "img_code_gen",
  },
  {
    id: "vox-synth",
    name: "VoxSynth",
    category: "Audio",
    description: "Lifelike text-to-speech and voice cloning.",
    longDescription:
      "Create realistic voiceovers, podcasts, and audio content with VoxSynth. Its advanced neural network produces speech that is virtually indistinguishable from a human. You can also clone your own voice for personalized audio projects.",
    features: ["Realistic Text-to-Speech", "Voice Cloning", "Multiple Languages & Accents", "Emotion Control"],
    rating: 4.7,
    url: "https://example.com/vox-synth",
    imageId: "img_voice_synth",
  },
  {
    id: "zenith-tasks",
    name: "Zenith Tasks",
    category: "Productivity",
    description: "Automatically organize and prioritize your to-do list.",
    longDescription:
      "Zenith Tasks is a smart task manager that learns your habits and priorities. It automatically sorts your tasks, suggests deadlines, and helps you focus on what's most important, ensuring you stay productive and organized.",
    features: ["Smart Prioritization", "Natural Language Task Input", "Project Timeline Generation", "Integration with Calendars"],
    rating: 4.5,
    url: "https://example.com/zenith-tasks",
    imageId: "img_task_manager",
  },
  {
    id: "pixel-perfect",
    name: "Pixel Perfect",
    category: "Image",
    description: "Enhance, upscale, and restore photos with a single click.",
    longDescription: "Give your old or low-quality photos a new life. Pixel Perfect uses AI to remove noise, increase resolution, and correct colors, turning blurry images into sharp, high-definition memories.",
    features: ["Image Upscaling", "Noise Reduction", "Color Correction", "Old Photo Restoration"],
    rating: 4.8,
    url: "https://example.com/pixel-perfect",
    imageId: "img_photo_enhancer",
  },
  {
    id: "logic-leap",
    name: "Logic Leap",
    category: "Code",
    description: "AI-powered debugger that finds issues before you do.",
    longDescription: "Logic Leap proactively scans your code to identify potential bugs, logical errors, and performance bottlenecks. It integrates with your IDE to provide real-time feedback and suggestions, streamlining the development process.",
    features: ["Real-time Bug Analysis", "Performance Profiling", "Security Vulnerability Scans", "IDE Integration"],
    rating: 4.7,
    url: "https://example.com/logic-leap",
    imageId: "img_code_debugger",
  },
  {
    id: "sonata-ai",
    name: "Sonata AI",
    category: "Audio",
    description: "Compose royalty-free music tailored to your needs.",
    longDescription: "Need a soundtrack for your video, game, or podcast? Sonata AI generates original, royalty-free music in any genre. Just describe the mood, tempo, and instruments, and get a unique composition in seconds.",
    features: ["Genre-based Music Generation", "Mood & Tempo Control", "Instrument Selection", "Royalty-Free Tracks"],
    rating: 4.6,
    url: "https://example.com/sonata-ai",
    imageId: "img_music_composer",
  },
  {
    id: "inbox-zero",
    name: "Inbox Zero",
    category: "Productivity",
    description: "Smart email assistant to categorize and summarize emails.",
    longDescription: "Tame your inbox with Inbox Zero. This AI tool automatically categorizes incoming mail, summarizes long threads, and drafts replies, helping you stay on top of your communication with minimal effort.",
    features: ["Automated Email Sorting", "Thread Summarization", "AI-assisted Reply Drafting", "Priority Filtering"],
    rating: 4.4,
    url: "https://example.com/inbox-zero",
    imageId: "img_email_sorter",
  },
  {
    id: "aether-logo",
    name: "Aether Logo",
    category: "Image",
    description: "Design a professional logo for your brand in minutes.",
    longDescription: "Aether Logo provides an intuitive platform to generate unique and professional logos. Describe your brand and style preferences, and the AI will produce a variety of design options that you can customize to perfection.",
    features: ["AI Logo Generation", "Style Customization", "Vector File Exports", "Brand Kit Creation"],
    rating: 4.7,
    url: "https://example.com/aether-logo",
    imageId: "img_logo_designer",
  },
  {
    id: "narrate-pro",
    name: "Narrate Pro",
    category: "Text",
    description: "Generate compelling scripts and screenplays.",
    longDescription: "From short film ideas to full-length feature screenplays, Narrate Pro assists writers in developing plots, creating characters, and formatting scripts. It's the perfect partner for any storyteller.",
    features: ["Plot & Character Generation", "Dialogue Assistance", "Automatic Formatting", "Story Arc Visualization"],
    rating: 4.5,
    url: "https://example.com/narrate-pro",
    imageId: "img_script_writer",
  },
  {
    id: "deploy-now",
    name: "Deploy Now",
    category: "Code",
    description: "Automated website builder and deployment tool.",
    longDescription: "Describe the website you want, and Deploy Now will generate the code, set up the infrastructure, and deploy it to the cloud. It's the fastest way to get your ideas online, from landing pages to full-stack applications.",
    features: ["Natural Language Website Design", "Full-Stack Code Generation", "Cloud Deployment", "CI/CD Pipeline Setup"],
    rating: 4.8,
    url: "https://example.com/deploy-now",
    imageId: "img_website_builder",
  }
];

export const categories = [...new Set(apps.map((app) => app.category))];
export type { AIApp, AppCategory };
